### ISSUE TITLE
Welp, I'm stuck again!

### ISSUE THREAD

**Issue by Jessica-Lee123** [Jessica-Lee123/modularity-mindfulness#1]
@thatkidmadrid 
I think I'm close, not fully grasping flex still, or css really, but I'm trying! Not sure if you can pinpoint anything for me. I know there's still tons wrong, my brain is just getting tired of the screen. I'm stepping away for a quick break just to re-fresh my brain. I will be back to see if there's anything else I can do before class time. If there's too much for you to help with, I totally get it, just mark me an X and I'll move on.

**Comment by thatkidmadrid** [comment]
I think you're definitely starting in the right place; start with the small screen layout then work your way up.

The first thing I notice is that you're trying to use the `display:contents` on your header. This is used to align items inside of an element onto a grid. This would be ok if you had a grid over everything - but even then, it may not be the best solution. This may be one big thing that's making things frustrating. 

Next, you're using description lists `<dl>` for the bottom area, but maybe another semantic tag may be better suited. A simple heading/paragraph pair is all you need here. This will also make styling easier as you won't need to override the default styling for description lists

I also notice you're missing the "Learn more ..." links on the three items 

```
<h1><i lang="ja">枯山水</i> <span>Rock Gardens</span></h1>
```

Here's an example of how to setup the first heading. We went over in class the use of the `<i>` tag quickly to be used similarly to a span to be able to style sections of text. I'll go over more about its use in class. In this activity it's used to wrap around all of the japanese text, as well as it allows us to style them to stack on top of the English text using `display: flex` + `flex-direction: column` on the header.

**Comment by Jessica-Lee123** [comment]
I just want to add very quickly (as I scramble to make these and other adjustments I just went over again, I am floored by the care you took into this response and I really appreciate it. Scrambling again now! See you in class! 
@thatkidmadrid

**Comment by Jessica-Lee123** [comment]
@thatkidmadrid @anna-pokhilenko
I'm so close! Two things I notice, the corner list of links on the top right isn't in links. 
The other is it's spanning vertically and not horizontally. 
I'll try to work on the link part now, see if I can figure it out, but the spanning is just cray cray!

**Comment by Jessica-Lee123** [comment]
Sorry, I just committed again, forgot to do that!

**Comment by thatkidmadrid** [comment]
For the links I think you probably know how to tackle that by using `<a href="#">` tags

Recall that flexbox was being used to alter the layout of the list. When you use `display:flex` on an element, it's children reflow using flexbox properties. By default it will already be `flex-direction: row` so you'll just need to add the styling to remove the bullets and modify the spacing to adjust to the small screen first, then to the larger screens

Can't stress enough how important it is to start with the small screen design, get that locked in, then tweak things using media queries to fit the larger screens. I have a feeling that you're developing based on a larger screen, so this should drive home the importance of starting with the smallest screen size because it will be much more difficult the other way around

**Comment by Jessica-Lee123** [comment]
I think that's what messed me up so badly, I did start with the big screen. I think I'm done with this though, I can't start over this late, gotta get my kid ready for her classes in the am. 
Thanks for being an awesome prof, you put a lot into your answers which is appreciated as I get it must be tedious af. Thank you to Anna too if you  reads this, nice to have someone extra there to help. Hope you two can get some sleep.

**Comment by thatkidmadrid** [comment]
if you want we can lump this one in with this week's activities, but I understand too if you want to just move on! I think it would be worth it for the grade and the practice
